server:
  port: 80

spring:
  application:
    name: cloud-feign-hystrix-order

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    register-with-eureka: false

feign:
  hystrix:
    enabled: true